pipeline {
	agent any

	stages {
		stage('Validate') {
			steps {
				sh 'test -f docker-basics/Dockerfile'
				sh 'test -f docker-basics/Dockerfile.app'
				echo 'Dockerfiles found successfully'
			}
		}


		stage('Build Docker Images') {
			steps {
				sh 'docker build -t devops-course-web:jenkins -f docker-basics/Dockerfile docker-basics'
				sh 'docker build -t devops-course-app:jenkins -f docker-basics/Dockerfile.app docker-basics'
			}
		}

		stage('Test web container') {
			steps {
				sh '''
					docker rm -f jenkins-web-test
					docker run -d --name jenkins-web-test -p 8081:80 devops-course-web:jenkins
					sleep 3
					curl --fail http://localhost:8081
					docker rm -f jenkins-web-test
				'''
			}
		}


		stage('Security Check') {
			steps {
				sh 'grep -q \"^FROM alpine:3.24.2\" docker-basics/Dockerfile.app'
				sh 'grep -q \"^USER appuser\" docker-basics/Dockerfile.app'
				echo 'Basic Docker security checks passed'
			}
		}

		stage('System Info') {
			steps {
				sh 'uname -a'
			}
		}
	}
}
