pipeline {
	agent any

	stages {
		stage('Validate') {
			steps {
				sh 'test -f docker-basics/Dockerfile'
				sh 'test -f docker-basics/Dockerfile.app'
				echo 'Dockerfiles found succesfully'
			}
		}

		stage('System Info') {
			steps {
				sh 'uname -a'
			}
		}
	}
}
